### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by akshayvinchurkar** [dotovr/tarsius-gtk-theme#1]
I want top bar font color white
![upload this](https://cloud.githubusercontent.com/assets/10510889/19995305/038a5fd4-a27c-11e6-8a65-463be079e39e.png)
see this its black now

next the when I hover on dock items the item name color is black i want white there also

**Comment by emhaye** [comment]
I see you using elementary OS (Pantheon DE), but i'm not used elementary OS.
Sorry, i'm could't to fix it.
I suggest you to use Gnome-Shell or [Manokwari Shell](https://github.com/BlankOn/manokwari) or you can use [BlankOn Linux](http://blankonlinux.or.id) with this [themes](https://github.com/dotovr/Taucho)

**Comment by akshayvinchurkar** [comment]
I like Elementary because it has that mac feel to it

**Comment by emhaye** [comment]
Yes it back to selection
